version: '3.5'

services:
  grafana:
    image: grafana/grafana
    ports: 
      - "3000:3000"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: module_kafka/
    ports:
      - "9092:9092"
      - "1099:1099"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "users:1:1"
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
    links:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  producer:
    build: module_producer/
    ports:
      - "9090:8989"
    links:
      - kafka
    depends_on:
      - zookeeper
      - kafka
    environment:
      kafka_host: kafka
      KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
  consumer:
    build: module_consumer/
    ports:
      - "8989:8989"
    links:
      - kafka
    depends_on:
      - kafka
      - producer
      - zookeeper
    environment:
      kafka_host: kafka
      KAFKA_BOOTSTRAP_SERVER: "kafka:9092"

