apiVersion: v1
kind: List
items:
        
  - apiVersion: v1
    kind: Service
    metadata:
      name: prometheus
    spec:
      selector:
        app: monitoring-prometheus
      type: NodePort
      ports:
        - name: port-prometheus
          port: 8080
          targetPort: 9090 
          nodePort: 30001
        - name: port-alertmanager
          port: 8085
          targetPort: 9093 
          nodePort: 30005
